[package]
name = "zng-webrender"
version = "0.65.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
license = "MPL-2.0"
repository = "https://github.com/zng-ui/zng-webrender"
description = "A GPU accelerated 2D renderer for web content"
build = "build.rs"
edition = "2018"
readme = "../FORK.md"

[features]
default = ["static_freetype"]
profiler = ["tracy-rs/enable_profiler"]
capture = ["api/serialize", "ron", "serde", "smallvec/serde", "etagere/serialization", "glyph_rasterizer/capture"]
replay = ["api/deserialize", "ron", "serde", "smallvec/serde", "etagere/serialization", "glyph_rasterizer/replay"]
display_list_stats = ["api/display_list_stats"]
serialize_program = ["serde", "webrender_build/serialize_program"]
dynamic_freetype = ["glyph_rasterizer/dynamic_freetype"]
static_freetype = ["glyph_rasterizer/static_freetype"]
leak_checks = []
sw_compositor = ["swgl"]

[build-dependencies]
build-parallel = "0.1.2"
glslopt = "0.1.11"
webrender_build = { version = "0.0.5", path = "../webrender_build", package = "zng-webrender-build" }

[dependencies]
bincode = "1.0"
bitflags = { version = "2", features = ["serde"] }
byteorder = "1.0"
euclid = { version = "0.22.10", features = ["serde"] }
fxhash = "0.2.1"
gleam = { workspace = true }
lazy_static = "1"
log = "0.4"
malloc_size_of_derive = "0.1"
num-traits = "0.2"
plane-split = "0.18"
png = { optional = true, version = "0.16" }
rayon = "1"
ron = { optional = true, version = "0.10.0" }
serde = { optional = true, version = "1.0", features = ["serde_derive"] }
smallvec = "1"
api = { version = "0.65.0", path = "../webrender_api", package = "zng-webrender-api" }
webrender_build = { version = "0.0.5", path = "../webrender_build", package = "zng-webrender-build" }
malloc_size_of = { version = "0.2.0", path = "../wr_malloc_size_of", package = "zng-wr-malloc-size-of" }
glyph_rasterizer = { version = "0.4.0", path = "../wr_glyph_rasterizer", package = "zng-wr-glyph-rasterizer", default-features = false }
svg_fmt = "0.4"
tracy-rs = "0.1.2"
derive_more = { version = "2", features = ["add_assign"] }
etagere = "0.2.13"
glean = { workspace = true, optional = true }
swgl = { path = "../swgl", optional = true, version = "0.4.0", package = "zng-swgl" }
topological-sort = "0.1"
peek-poke = { version = "0.4.0", path = "../peek-poke", package = "zng-peek-poke" }
allocator-api2 = { version = "0.2.18", features = ["alloc", "serde"] }

[dev-dependencies]
mozangle = "0.5.2"
rand = "0.4"
